get http://localhost:3000/dev/cars

#####

post http://localhost:3000/dev/cars
Content-Type: application/json

{
    "id" : "wq45dsf", 
    "name" : "Get delete requests working"
}

#####

delete http://localhost:3000/dev/cars/e6c66a31-fa50-41ec-b9ea-16e1704b2361"